-- Active: 1732285628768@@45.10.110.58@60100@chainrpc

CREATE TABLE IF NOT EXISTS account (
  id SERIAL PRIMARY KEY,
  address TEXT UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nonce (
  id SERIAL PRIMARY KEY,
  address TEXT UNIQUE,
  nonce TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS access_token (
  id SERIAL PRIMARY KEY,
  token TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deactivated_at TIMESTAMP DEFAULT NULL
) 

CREATE TABLE IF NOT EXISTS api_key (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES account(id),
  api_key TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS priority (
  id SERIAL PRIMARY KEY,
  chain TEXT NOT NULL,
  hostname TEXT NOT NULL,
  weight INTEGER NOT NULL
)